var roleEnum = {
  ADMIN : 'ADMIN',
  PATIENT : 'PATIENT',
  HCP : 'HCP',
  ACCT_SERVICES : 'ACCT_SERVICES',
  ASSOCIATES : 'ASSOCIATES',
  HILLROM_ADMIN : 'HILLROM_ADMIN',
  CLINIC_ADMIN : 'CLINIC_ADMIN',
  ANONYMOUS : 'ANONYMOUS',
  CUSTOMER_SERVICES : 'CUSTOMER_SERVICES',
  FOTAAdmin : 'FOTA_ADMIN',
  FOTAApprover : 'FOTA_APPROVER'

};